name = "that time i was made to scape while running from a parasite while trying to set up industrial systems for my liquid concrete"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
unsup = "1.2.7"

[options]
no-internal-hashes = true
